#!/bin/ash

MARDOCK_CWD="/home/mardock/mardock"

case "${1}" in
  "start") exec /docker-entrypoint-start.sh ;;
  "build") exec /docker-entrypoint-build.sh ;;
  "export") exec /docker-entrypoint-export.sh ;;
  "develop") exec /docker-entrypoint-develop.sh ;;
esac

exec echo "docker run [OPTIONS] mardock:latest [start | build | export | develop]"
