#!/bin/ash

MARDOCK_CWD="/home/mardock/mardock"

case "${1}" in
  "build") exec /docker-entrypoint-build.sh ;;
  "develop") exec /docker-entrypoint-develop.sh ;;
esac

exec echo "docker run [OPTIONS] mardock:latest [build | develop]";;
